datasets:
    ilsvrc2012:
        name: &dataset_name 'ilsvrc2012'
        type: 'imagefolder'
        root: &root_dir !join ['./resource/dataset/', *dataset_name]
        rough_size: 342
        input_size: [299, 299]
        splits:
            train:
                dataset_id: &imagenet_train !join [*dataset_name, '/train']
                images: !join [*root_dir, '/train']
                data_aug: True
            val:
                dataset_id: &imagenet_val !join [*dataset_name, '/val']
                images: !join [*root_dir, '/val']
                data_aug: False
        normalizer:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]

models:
    teacher_model:
        name: &teacher_model_name 'inception_v3'
        params:
            num_classes: 1000
            pretrained: True
        experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
        ckpt: !join ['./resource/ckpt/image_classification/teacher/', *teacher_experiment, '.pt']
    student_model:
        name: &student_model_name 'custom_inception_v3'
        params:
            bottleneck_channel: 12
            bottleneck_idx: 7
            compressor:
            decompressor:
            num_classes: 1000
            pretrained: True
        experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_from_', *teacher_model_name]
        ckpt: !join ['./resource/ckpt/image_classification/single_stage/ghnd/', *student_experiment, '.pt']

train:
    log_freq: 1000
    num_epochs: 20
    train_data_loader:
        dataset_id: *imagenet_train
        random_sample: True
        batch_size: 32
        num_workers: 16
        cache_output:
    val_data_loader:
        dataset_id: *imagenet_val
        random_sample: False
        batch_size: 32
        num_workers: 16
    teacher:
        adaptations:
            maxpool1:
                type: 'MaxPool2d'
                params:
                    kernel_size: 3
                    stride: 2
            maxpool2:
                type: 'MaxPool2d'
                params:
                    kernel_size: 3
                    stride: 2
        sequential: ['Conv2d_1a_3x3', 'Conv2d_2a_3x3', 'Conv2d_2b_3x3', '+maxpool1', 'Conv2d_3b_1x1', 'Conv2d_4a_3x3', '+maxpool2', 'Mixed_5b', 'Mixed_5c', 'Mixed_5d', 'Mixed_6a', 'Mixed_6b', 'Mixed_6c', 'Mixed_6d', 'Mixed_6e', 'Mixed_7a', 'Mixed_7b', 'Mixed_7c']
        frozen_modules: []
        forward_hook:
            input: []
            output: ['+maxpool2', 'Mixed_5d', 'Mixed_6e', 'Mixed_7c']
        wrapper:
        requires_grad: False
    student:
        adaptations:
        sequential: ['bottleneck', 'Mixed_5b', 'Mixed_5c', 'Mixed_5d', 'Mixed_6a', 'Mixed_6b', 'Mixed_6c', 'Mixed_6d', 'Mixed_6e', 'Mixed_7a', 'Mixed_7b', 'Mixed_7c']
        frozen_modules: ['Mixed_5b', 'Mixed_5c', 'Mixed_5d', 'Mixed_6a', 'Mixed_6b', 'Mixed_6c', 'Mixed_6d', 'Mixed_6e', 'Mixed_7a', 'Mixed_7b', 'Mixed_7c']
        forward_hook:
            input: []
            output: ['bottleneck', 'Mixed_5d', 'Mixed_6e', 'Mixed_7c']
        wrapper:
        requires_grad: True
    apex:
        requires: False
        opt_level: '01'
    optimizer:
        type: 'Adam'
        params:
            lr: 0.001
    scheduler:
        type: 'MultiStepLR'
        params:
            milestones: [5, 10, 15]
            gamma: 0.1
    criterion:
        type: 'GeneralizedCustomLoss'
        org_term:
            factor: 0.0
        sub_terms:
            maxpool2:
                criterion:
                    type: 'MSELoss'
                    params:
                        reduction: 'sum'
                params:
                    input:
                        is_from_teacher: False
                        module_path: 'bottleneck'
                        io: 'output'
                    target:
                        is_from_teacher: True
                        module_path: '+maxpool2'
                        io: 'output'
                factor: 1.0
            Mixed_5d:
                criterion:
                    type: 'MSELoss'
                    params:
                        reduction: 'sum'
                params:
                    input:
                        is_from_teacher: False
                        module_path: 'Mixed_5d'
                        io: 'output'
                    target:
                        is_from_teacher: True
                        module_path: 'Mixed_5d'
                        io: 'output'
                factor: 1.0
            Mixed_6e:
                criterion:
                    type: 'MSELoss'
                    params:
                        reduction: 'sum'
                params:
                    input:
                        is_from_teacher: False
                        module_path: 'Mixed_6e'
                        io: 'output'
                    target:
                        is_from_teacher: True
                        module_path: 'Mixed_6e'
                        io: 'output'
                factor: 1.0
            Mixed_7c:
                criterion:
                    type: 'MSELoss'
                    params:
                        reduction: 'sum'
                params:
                    input:
                        is_from_teacher: False
                        module_path: 'Mixed_7c'
                        io: 'output'
                    target:
                        is_from_teacher: True
                        module_path: 'Mixed_7c'
                        io: 'output'
                factor: 1.0

test:
    test_data_loader:
        dataset_id: *imagenet_val
        random_sample: False
        batch_size: 1
        num_workers: 16

