datasets:
    ilsvrc2012:
        name: &dataset_name 'ilsvrc2012'
        type: 'imagefolder'
        root: &root_dir !join ['./resource/dataset/', *dataset_name]
        rough_size: 256
        input_size: [224, 224]
        splits:
            train:
                dataset_id: &imagenet_train !join [*dataset_name, '/train']
                images: !join [*root_dir, '/train']
                data_aug: True
            val:
                dataset_id: &imagenet_val !join [*dataset_name, '/val']
                images: !join [*root_dir, '/val']
                data_aug: False
        normalizer:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]

models:
    teacher_model:
        name: &teacher_model_name 'resnet50'
        params:
            num_classes: 1000
            pretrained: True
        experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
        ckpt: !join ['./resource/ckpt/teacher/', *teacher_experiment, '.pt']

    student_model:
        name: &student_model_name 'resnet18'
        params:
            num_classes: 1000
            pretrained: True
        experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_from_', *teacher_model_name]
        ckpt: !join ['./resource/ckpt/single_stage/cckd/', *student_experiment, '.pt']

train:
    log_freq: 1000
    num_epochs: 20
    train_data_loader:
        dataset_id: *imagenet_train
        random_sample: True
        batch_size: 32
        num_workers: 16
        cache_output:
    val_data_loader:
        dataset_id: *imagenet_val
        random_sample: False
        batch_size: 32
        num_workers: 16
    teacher:
        sequential: []
        special:
            type: 'Linear4CCKD'
            params:
                input_module_path: 'model.layer4'
                linear_params_config:
                    in_features: 2048
                    out_features: 128
                    bias: True
        forward_hook:
            input: []
            output: ['model.layer4']
        wrapper:
        requires_grad: True
        frozen_modules: ['model']
    student:
        adaptations:
        sequential: []
        special:
            type: 'Linear4CCKD'
            params:
                input_module_path: 'model.layer4'
                linear_params_config:
                    in_features: 512
                    out_features: 128
                    bias: True
        forward_hook:
            input: []
            output: ['model.layer4']
        wrapper:
        requires_grad: True
        frozen_modules: []
    apex:
        requires: False
        opt_level: '01'
    optimizer:
        type: 'SGD'
        params:
            lr: 0.0001
            momentum: 0.9
            weight_decay: 0.0005
    scheduler:
        type: 'MultiStepLR'
        params:
            milestones: [5, 15]
            gamma: 0.1
    criterion:
        type: 'GeneralizedCustomLoss'
        org_term:
            criterion:
                type: 'KDLoss'
                params:
                    temperature: 1.0
                    alpha: 0
                    reduction: 'batchmean'
            factor: 1.0
        sub_terms:
            cckd:
                criterion:
                    type: 'CCKDLoss'
                    params:
                        teacher_linear_path: 'model.avgpool'
                        student_linear_path: 'model.avgpool'
                        reduction: 'batchmean'
                factor: 0.003

test:
    test_data_loader:
        dataset_id: *imagenet_val
        random_sample: False
        batch_size: 1
        num_workers: 16
